on:
  push:
    paths:
      - ci/**
  pull_request:
    paths:
      - ci/**

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Unit Tests for CI
        run: npm run test-ci
