on:
  pull_request:
    branches:
      - main

jobs:
  validate_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Validate Registry
        run: node ci/check-registry.js
      - name: Validate Early Adopters
        run: node ci/check-early-adopters.js
